"""
Constants module for Pawlygon Utils addon.

Contains configuration data for shapekey operations including:
- Vertex group pairs for splitting shapekeys (e.g., Left/Right, Upper/Lower)
- Predefined shapekey lists for checking missing keys (Unified Expressions, ARKit)
"""

# Vertex group pairs used for splitting shapekeys
# Each tuple defines two complementary vertex groups
# When splitting, creates two new shapekeys: one for each group
VERTEX_GROUP_PAIRS = [
    ("Left", "Right"),
    ("Upper", "Lower"),
]

# Predefined shapekey lists for facial animation standards
# Used to check objects for missing required shapekeys
SHAPEKEY_LISTS = {
    "Unified Expressions": [
        "BrowDown",
        "BrowDownRight",
        "BrowDownLeft",
        "BrowInnerUp",
        "BrowInnerUpLeft",
        "BrowInnerUpRight",
        "BrowOuterUp",
        "BrowOuterUpLeft",
        "BrowOuterUpRight",
        "EyeClosed",
        "EyeClosedLeft",
        "EyeClosedRight",
        "EyeConstrict",
        "EyeDilation",
        "EyeLookDown",
        "EyeLookDownLeft",
        "EyeLookDownRight",
        "EyeLookIn",
        "EyeLookInLeft",
        "EyeLookInRight",
        "EyeLookOut",
        "EyeLookOutLeft",
        "EyeLookOutRight",
        "EyeLookUp",
        "EyeLookUpLeft",
        "EyeLookUpRight",
        "EyeSquint",
        "EyeSquintLeft",
        "EyeSquintRight",
        "EyeWide", 
        "EyeWideLeft",
        "EyeWideRight",
        "CheekPuff",
        "CheekPuffLeft",
        "CheekPuffRight",
        "CheekSquint",
        "CheekSquintLeft",
        "CheekSquintRight",
        "CheekSuck",
        "CheekSuckLeft",
        "CheekSuckRight",
        "LipFunnel",
        "LipFunnelLower",
        "LipFunnelUpper",
        "LipPucker",
        "LipSuckLower",
        "LipSuckUpper",
        "JawForward",
        "JawLeft",
        "JawOpen",
        "JawRight",
        "MouthClosed",
        "MouthFrown",
        "MouthFrownLeft",
        "MouthFrownRight",
        "MouthLeft",
        "MouthLowerDown",
        "MouthPress",
        "MouthRaiser",
        "MouthRaiserLower",
        "MouthRaiserUpper",
        "MouthRight",
        "MouthSmile",
        "MouthSmileLeft",
        "MouthSmileRight",
        "MouthStretch",
        "MouthStretchLeft",
        "MouthStretchRight",
        "MouthTightener",
        "MouthTightenerLeft",
        "MouthTightenerRight",
        "MouthUpperUp",
        "MouthUpperUpLeft",
        "MouthUpperUpRight",
        "NoseSneer",
        "NoseSneerLeft",
        "NoseSneerRight",
        "TongueDown",
        "TongueLeft",
        "TongueOut",
        "TongueRight",
        "TongueUp",
    ],
    "ARKit": [
        "eyeBlinkLeft",
        "eyeBlinkRight",
        "eyeWideLeft",
        "eyeWideRight",
        "eyeSquintLeft",
        "eyeSquintRight",
        "eyeLookDownLeft",
        "eyeLookDownRight",
        "eyeLookInLeft",
        "eyeLookInRight",
        "eyeLookOutLeft",
        "eyeLookOutRight",
        "eyeLookUpLeft",
        "eyeLookUpRight",
        "browDownLeft",
        "browDownRight",
        "browInnerUp",
        "browOuterUpLeft",
        "browOuterUpRight",
        "cheekPuff",
        "cheekSquintLeft",
        "cheekSquintRight",
        "noseSneerLeft",
        "noseSneerRight",
        "jawOpen",
        "jawForward",
        "jawLeft",
        "jawRight",
        "mouthClose",
        "mouthFunnel",
        "mouthPucker",
        "mouthLeft",
        "mouthRight",
        "mouthSmileLeft",
        "mouthSmileRight",
        "mouthFrownLeft",
        "mouthFrownRight",
        "mouthDimpleLeft",
        "mouthDimpleRight",
        "mouthStretchLeft",
        "mouthStretchRight",
        "mouthRollLower",
        "mouthRollUpper",
        "mouthShrugLower",
        "mouthShrugUpper",
        "mouthPressLeft",
        "mouthPressRight",
        "mouthLowerDownLeft",
        "mouthLowerDownRight",
        "mouthUpperUpLeft",
        "mouthUpperUpRight",
        "tongueOut",
    ],
}
